export const ACTIVE_NUMBER_CLASS = 'ACTIVE_NUMBER_CLASS ';
export const ACTIVE_MONTH_CLASS = 'ACTIVE_MONTH_CLASS';
export const ACTIVE_YEAR_CLASS = 'ACTIVE_YEAR_CLASS';

export const ACTIVE_CODE_CLASS ='ACTIVE_CODE_CLASS';
